name: Podman CI/CD on Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build Docker image with Podman
        run: |
          podman build . --file Dockerfile --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:${GITHUB_SHA::7}
          podman tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:${GITHUB_SHA::7} gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:latest

      - name: Authenticate to Google Cloud Registry
        env:
          GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}
        run: |
          echo "${GCP_SA_KEY_BASE64}" | base64 --decode > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          gcloud auth configure-docker gcr.io

      - name: Push Docker image to Google Cloud Registry
        run: |
          podman push gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:${GITHUB_SHA::7}
          podman push gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Authenticate with Kubernetes
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f path/to/deployment.yaml
