name: Podman CI/CD on Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build Docker image with Podman
        run: |
          podman build . --file Dockerfile --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:${GITHUB_SHA::7}
          podman tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:${GITHUB_SHA::7} gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:latest

      - name: Log in to Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Push Docker image to Google Container Registry
        run: |
          podman push gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:${GITHUB_SHA::7}
          podman push gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:latest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy podman-demo --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/podman-demo:latest --platform=managed --region=us-central1 --allow-unauthenticated
